In [29]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [14]:
items = ['Tv','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

### 먼저 숫자값으로 변환하기 위해 label encoding을 합니다 


In [15]:
# LabelEncoding을 통해 1차원 배열로 만들어 줍니다.
encoder = LabelEncoder()
encoder.fit(items)

LabelEncoder()

In [16]:
labels = encoder.transform(items)

In [17]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [19]:
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

### One-Hot-Encoding

In [22]:
oh_encoder= OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)

In [28]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

## pandas의 get_dummies()를 이용한 One-Hot Encoding

In [30]:
df = pd.DataFrame({'items' : ['Tv','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
df

items
0     Tv
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [31]:
pd.get_dummies(df)

items_Tv  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0